### PR TITLE
add Id field to Shape

### PR DESCRIPTION
**Pull request by joeshaw**
Makes it possible to do shape ID-based lookups

### CODE REVIEW

**Comment by patrickbr** [comment]
Hi, thanks for you contribution! Could you elaborate a bit on why you need to have the shape ID? Our basic idea was to see the GTFS entity ids as mere references other entities can use as a foreign key and replace them by references to the actual entity to save a) memory, b) the need for a lookup table and c) the time needed for lookup table requests. So we actually planned on removing the remaining id members from route, trip and agency.

For writing GTFS back into a CSV, we plan to use dense integer ids which are generated on-the-fly. However, we may have missed scenarios where the explicit id as stored in the input data could be of use.

**Comment by joeshaw** [comment]
> Could you elaborate a bit on why you need to have the shape ID?

It was a convenience for de-duplication by using it as a map key.  I can instead walk the (relatively small) number of shapes and check for pointer equality instead.  If you'd rather not add it, I'm fine with closing this PR.

> So we actually planned on removing the remaining id members from route, trip and agency.

I strongly discourage this as it'll harm interoperability with other services.  For instance, the MBTA uses GTFS route and trip IDs in its API (see http://realtime.mbta.com/Portal/Home/Documents).  I use the route ID in gtfsparser to generate KML files containing all the shapes for a given route and save them to files named `<route_id>.kml`.  In my app I take the route ID from the API and use it to download the matching KML file.  I'm not sure I can use the library if those IDs are removed, as the mapping to the canonical values will be lost.

**Comment by patrickbr** [comment]
> I strongly discourage this as it'll harm interoperability with other services. For instance, the MBTA uses GTFS route and trip IDs in its API (see http://realtime.mbta.com/Portal/Home/Documents).

You are absolutely right, this is a valid point. As I was reading your comment, it came to me that GTFS-realtime also makes heavy use of id references, and not storing the IDs would make the library useless to people trying to enrich static data with realtime data.

Since the ids are valuable information, they should be consistently stored.

**Comment by joeshaw** [comment]
Thanks a lot!

**Pull request merged**
